# Base prompt components
base_prompt:
  subject: "A photorealistic black labrador retriever"
  modification: "with its head replaced by a realistic snake head"
  integration: "The snake head should be seamlessly integrated, creating a surreal but cohesive hybrid creature"
  posture: "The lab's body posture and proportions should be natural for the activity"

# Activities the snake-headed lab can be doing
activities:
  - "running through a forest trail with joy"
  - "jumping to catch a tennis ball in mid-air"
  - "playing fetch in a sunny park"
  - "splashing in a lake"
  - "chasing a frisbee on the beach"
  - "rolling in autumn leaves"
  - "digging enthusiastically in the garden"
  - "playing with other dogs at the dog park"
  - "swimming in a pool"
  - "catching treats in mid-air"
  - "playing tug-of-war with a rope toy"
  - "running through sprinklers on a hot day"
  - "sitting proudly on a mountain summit at sunrise"
  - "leaping over fallen logs in a misty forest"
  - "napping peacefully in a patch of sunlight"
  - "paddling on a surfboard in gentle waves"
  - "playing in fresh snow with excitement"
  - "carrying a stick twice its size with determination"
  - "chasing butterflies in a wildflower meadow"
  - "retrieving a floating toy from a pond"
  - "racing alongside a bicycle on a path"
  - "herding sheep in a green pasture"
  - "jumping through agility course hoops"
  - "pulling a sled through snowy terrain"
  - "exploring a cave entrance with curiosity"
  - "balancing on a stand-up paddleboard"
  - "participating in a dog show ring"
  - "guarding a campsite at dusk"
  - "playing soccer with its nose"
  - "doing tricks for treats in the kitchen"
  - "investigating rabbit holes in the woods"
  - "walking through a pumpkin patch"
  - "helping dig up garden vegetables"
  - "playing hide and seek behind trees"
  - "catching snowballs in winter"
  - "wading through a shallow stream"
  - "chasing its tail in circles"
  - "sitting in a kayak on a calm lake"
  - "running alongside horses in a field"
  - "playing with bubbles in the backyard"
  - "carrying a basket of tennis balls"
